disabled_rules:
  - trailing_whitespace
  - identifier_name
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - large_tuple
  - force_cast
  - multiple_closures_with_trailing_closure

opt_in_rules: []

analyzer_rules:
  - unused_declaration
  - unused_import

included:
  - Timeline

excluded:
  - Timeline.xcodeproj
  - Timeline.xcworkspace

reporter: "xcode"
