// Copyright (c) 2025 Amir Kiani
// SPDX-License-Identifier: MIT

import Foundation

/// A concise, literacy-level summary item for a care event.
struct SummaryEvent: Codable, Identifiable {
    let id = UUID()
    let headline: String
    let subheadline: String
    let body: String
    
    private enum CodingKeys: String, CodingKey {
        case headline, subheadline, body
    }
}

/// Response container for a cluster-level summary generated by AI.
struct ClusterSummaryResponse: Codable {
    let events: [SummaryEvent]
}
